### ISSUE TITLE
RDS Plugin: See an error related to the logging stuff when terminating

### ISSUE THREAD

**Issue by MitchellGerdisch** [rightscale/rightscale-plugins#33]
When I terminate the CAT found here:
https://github.com/RightScale-Demo/ss_assets/tree/master/Docker-WordPress_RDS_backend

I get the error shown below in SS.

If I terminate the now "Failed" cloud app, it will get to a terminated state. So the problem only occurs the first time through.

SS ERROR:
```
terminate failed:

Problem:
  JSON value assigned to reference
Origin:
  line: 380, column: 10
    definition: rs_aws_rds.sys_log.detail
    task: /root/1
    expression: @audit = $$audits[task_name()]
Summary:
  JSON values must be assigned to variables such as $foo and not references such as @audit
Resolution:
  Use a variable to assign JSON values
```
